### ISSUE TITLE
since 0.6.1 track-o-bot stopped tracking

### ISSUE THREAD

**Issue by angrylinuxuser** [BOSSoNe0013/track-o-bot#20]
After updating to 0.6.1 track-o-bot isn't tracking games anymore. Nothing changed in my setup so its not a configuration  fault, also i have 0.4.6 backed up and that version is tracking games.

As a side note. A new file is created in a directory containg Track-o-bot binary called C:\tmp\out.txt that contains a string Hearthstone (looks like a offline cache thingy). There might be a issue with this if you dont have rights to write to a folder. Would it be reasonable to create this file in  ~/.Hearthstone?

**Comment by BOSSoNe0013** [comment]
Hi,
you can remove the tmp file, it's no more created in latest revision. I'm checking the tracking system.
Thanks

**Comment by hplgonzo** [comment]
First of all thanks for bringing Hearthstone Tracking support to Linux operating systems.
v0.6.1 not tracking confirmed.

Last working version (v0.5.0) I had to set up like this (https://www.reddit.com/r/trackobot/comments/3ggdon/trackobot_not_working_linux/) to track my games, but this doesn't work with v0.6.1 anymore.

Did ToB always modify the log.config file to look like this on start?
http://pastebin.com/Um6vJ8F6
Originally I set up and symlinked that file as advised by the reddit post (https://www.reddit.com/r/hearthstone/comments/268fkk/simple_hearthstone_logging_see_your_complete_play). 
It seems a little bit weird. Especially lines 3 & 4.

This entry in "~/.local/share/spidy.ch/Track-o-Bot/Track-o-Bot.log" also seems strange and did not occur in v0.5.0: http://pastebin.com/gHbnDwgb
I symlinked "[WINEPREFIX]/drive_c/users/Public/Application Data/Battle.net/Agent/agent.db" to "~/.Hearthstone" to get rid of the error message, however ToB is not tracking any games.

Let me know, if I can provide you with more information. It would be great to track games again.
By the way, I am running that version of ToB: https://aur.archlinux.org/packages/track-o-bot-git

**Comment by terzag** [comment]
Same issue for me. Except that my log.config file hasn't changed (I suppose). I don't have the doubled line like hplgonzo. Are you using other softwares? I seem to remember people on Windows having similar problems of modified config file when using another deck tracker which is incompatible with Track-o-Bot.

**Comment by hplgonzo** [comment]
Hi terzag.

Well, as soon as I start the Linux version, "log.config" gets modified in that weird way. The Windows version leaves "log.config" untouched.

Nope, I am not using any other tracking software. Is there even tracking software out there, that runs on Linux? At the moment I use the Windows version via wine, because it tracks my games. I haven't tried the Linux version since then. Anyway as a Linux user I really would prefer to use the Linux version. So tell me, if I can give you some more information.

"log.config" is currently set up like that:
http://pastebin.com/w65ygHM5

I wonder what the other loggers, mentioned in the reddit posting, do. In the next few days, I will include them in my "log.config" and check the resulting log files. Maybe some of them are logging interesting or useful stuff.

By the way is it possible to "comment" lines within "log.config", as you can do in shell scripts, xml, C, ...
For example:
# ZONE: contains players and opponents cards, board position, ...
[ZONE]
...
/* BOB: shows your legend rank ... */
/* [BOB] */
/* ... */

I guess you know what I mean by that.

If so, we could create a global "log.config" file, which includes all possible loggers and only the sections needed (ZONE) would be "uncommented". I'm just curious and haven't tried so far, so perhaps you know the answer already. After installing ToB you just move the pre-configured "log.config" to the correct folder, symlink it and there you go.

Sidenote: This time around I stored and wrote down my ToB log in credentials. Too bad I lost my account last week because of my own stupidity. *lol

**Comment by terzag** [comment]
All I know, is that there are other tracking softwares (don't know if they run with Wine) that modify the log.config file in a way that's incompatible with Track-o-Bot. It looks like every developer uses one way to track the games except the one who develop Track-o-Bot (Windows version), who decided to use another way because he says it's better. I.e. the other softwares read the "console" (not sure what that means) while Track-o-Bot reads the log file, which takes apparently far less resources.

So all I can say is that I've seen similar report on Reddit showing the log file modified with lines that are doubled and it was by other trackers, from what I've understood.

**Comment by angrylinuxuser** [comment]
Well that issue pissed me off so i went through the source code to understand what's going on even though my programming skills ended at C++ with STL. So after 30 minutes of code reading and small  debugging session and i figured it out :)

Beetween 0.5 and 0.6 trackobot stopped using output_log.txt to log data and started using Power.log Zone.log Asset.log and Bob.log instead. So solution to our problem is to simply symlink Logs directory from your Hearthstone installation in wineprefix to ~/.Hearthstone/Logs.
For instance:
 ln -s ~/.wine/drive_c/Program Files/Hearthstone/Logs/ ~/.Hearthstone/Logs

Now the only thing left to to is to update FAQ at the main repo page to include this info.

Hope it helps :)

**Comment by BOSSoNe0013** [comment]
Hi,
REAME is now up to date. Sorry, i was on mass work last week. Track-o-Bot for Linux is now sync with latest 0.6.2 and everything should work correctly.
Have a nice day

**Comment by Strit** [comment]
I'm sorry, but I still have no tracking with version 0.6.1 (i believe the windows version is at 0.6.2). Yes I have symlinked the Logs folder and the log.config file.
