### ISSUE TITLE
No overlay or profile page with new version

### ISSUE THREAD

**Issue by wavecycle** [BOSSoNe0013/track-o-bot#76]
Hi, I just recompiled off github for Ubuntu 16.10. The new version is up and running, however there is no overlay and if I try view the profile it just opens up an empty browser page.

I can see the new icons in the menu and everything looks fine in the log ie no errors, seems to be picking up each action, although if I play games I can see the card names mentioned and there are no new cards there.

Thanks!

**Comment by angrylinuxuser** [comment]
So:
Empty browser page it's badly written desktop file for google chrome ( 'im pretty sure you are using google chrome ). To fix this edit ~/.local/share/applications/google-chrome.desktop and add %U to the line starting with Exec so it looks like this:
Exec=/opt/google/chrome/chrome %U

I have ubuntu 16.10 installed and overlay works fine with unity and gnome 3. ( Could you check if you enabled overlay? ) If the issue is still present could you check if overlay works for windowed/fullscreen.

Im assuming you are talking about cards from new expanion not beeing sent to ToB server and not displayed in your profile? I noticed this in one game i played since yesterday and this appears to be upstream prbolem.

**Comment by wavecycle** [comment]
It turns out I was running 16.04. I updated to 16.10 and all is working now, thanks!

**Comment by angrylinuxuser** [comment]
what about google chrome? is it launching profile correclty?

**Comment by wavecycle** [comment]
Yes thanks, forgot to mention that..the change you detailed has it launching properly now. :)
